### ISSUE TITLE
 Tính năng theo nhạc không còn ở bạn 3.0.1. Các thiết bị chọn nguồn phát trong app trống( 3.0.1 beta 2)

### ISSUE THREAD

**Issue by Invisible-93** [Kaitoukid93/Ambinity#31]
## Mô tả Bug
Lựa chọn `Nguồn phát` trống trong tính năng `nháy theo nhạc`, dẫn đến tính năng `nháy theo nhạc` không hoạt động

## Khi nào thì xảy ra Bug ( Steps to ReProduce)
Các bước đã làm:
1. Mở App
2. Chọn Chế độ `Nháy theo nhạc`
3. Click chọn `Nguồn phát`
4. Không hiển thị các nguồn phát hiện có

## Mong muốn (Expected behavior)
Chọn được nguồn phát từ đó led sẽ nháy theo nguồn phát đã chọn

## Ảnh chụp (Screenshots)
...

## Cấu hình sử dụng(Điền đầy đủ):
 - OS: [e.g. Windows 10,11...]
 - Cỡ màn hình :tất cả các cỡ màn hình
 - Sản phẩm sử dụng : tất cả các sản phẩm
 - Phiên bản App sử dụng : `3.0.1 public beta 2`

## Thông tin thêm
...

**Comment by Kaitoukid93** [comment]
#21

**Comment by Kaitoukid93** [comment]
Thiếu Bass.dll, will be fixed in public Beta 2
